name: Auto Login to Searcade

on:
  schedule:
    # 每三天执行一次，UTC时间00:00
    - cron: '0 0 */3 * *'
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]  # 有修改时也执行
  pull_request:
    branches: [ main ]

jobs:
  login:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Playwright
      run: |
        npm init -y
        npm install playwright
        npx playwright install chromium
        
    - name: Auto Login
      env:
        LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      run: |
        cat > login.js << 'EOF'
        const { chromium } = require('playwright');
        
        (async () => {
          const browser = await chromium.launch();
          const page = await browser.newPage();
          
          try {
            console.log('访问登录页面...');
            await page.goto('https://searcade.userveria.com/login');
            
            console.log('等待页面加载...');
            await page.waitForLoadState('networkidle');
            
            console.log('查找并填写邮箱...');
            await page.fill('input[name="email"]', process.env.LOGIN_EMAIL);
            
            console.log('查找并填写密码...');
            await page.fill('input[name="password"]', process.env.LOGIN_PASSWORD);
            
            console.log('点击登录按钮...');
            await page.click('button[type="submit"]');
            
            console.log('等待登录完成...');
            await page.waitForLoadState('networkidle');
            
            console.log('检查登录结果...');
            const currentUrl = page.url();
            console.log('当前URL:', currentUrl);
            
            if (currentUrl.includes('searcade.com/en/admin')) {
              console.log('✅ 登录成功！');
            } else {
              console.log('❌ 登录失败，当前URL:', currentUrl);
              process.exit(1);
            }
            
          } catch (error) {
            console.error('❌ 登录失败:', error.message);
            process.exit(1);
          } finally {
            await browser.close();
          }
        })();
        EOF
        
        node login.js
