name: Auto Login to Searcade

on:
  schedule:
    # 每三天执行一次，UTC时间00:00
    - cron: '0 0 */3 * *'
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]  # 有修改时也执行
  pull_request:
    branches: [ main ]

jobs:
  login:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install puppeteer@19.11.1
        
    - name: Auto Login
      env:
        LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      run: |
        cat > login.js << 'EOF'
        const puppeteer = require('puppeteer');
        
        (async () => {
          let browser;
          try {
            console.log('启动浏览器...');
            browser = await puppeteer.launch({
              headless: true,
              args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-gpu',
                '--disable-web-security',
                '--disable-features=VizDisplayCompositor'
              ]
            });
            
            const page = await browser.newPage();
            
            // 设置用户代理
            await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36');
            
            // 设置页面大小
            await page.setViewport({ width: 1280, height: 720 });
            
            console.log('访问登录页面...');
            const response = await page.goto('https://searcade.userveria.com/login', {
              waitUntil: 'networkidle2',
              timeout: 60000
            });
            
            console.log('页面响应状态:', response.status());
            console.log('页面URL:', page.url());
            
            // 等待页面完全加载
            await new Promise(resolve => setTimeout(resolve, 3000));
            
            // 获取页面标题和内容，用于调试
            const title = await page.title();
            console.log('页面标题:', title);
            
            // 检查页面是否包含登录表单
            const pageContent = await page.content();
            const hasEmailInput = pageContent.includes('name="email"');
            const hasPasswordInput = pageContent.includes('name="password"');
            console.log('页面是否包含email输入框:', hasEmailInput);
            console.log('页面是否包含password输入框:', hasPasswordInput);
            
            if (!hasEmailInput || !hasPasswordInput) {
              console.log('页面HTML内容片段:');
              console.log(pageContent.substring(0, 2000) + '...');
            }
            
            console.log('等待登录表单加载...');
            // 使用多种选择器尝试
            const emailSelector = await Promise.race([
              page.waitForSelector('input[name="email"]', { timeout: 15000 }).then(() => 'input[name="email"]'),
              page.waitForSelector('#email_input', { timeout: 15000 }).then(() => '#email_input'),
              page.waitForSelector('input[type="text"]', { timeout: 15000 }).then(() => 'input[type="text"]')
            ]).catch(() => null);
            
            const passwordSelector = await Promise.race([
              page.waitForSelector('input[name="password"]', { timeout: 15000 }).then(() => 'input[name="password"]'),
              page.waitForSelector('#password_input', { timeout: 15000 }).then(() => '#password_input'),
              page.waitForSelector('input[type="password"]', { timeout: 15000 }).then(() => 'input[type="password"]')
            ]).catch(() => null);
            
            if (!emailSelector || !passwordSelector) {
              console.log('❌ 无法找到登录表单元素');
              console.log('邮箱输入框选择器:', emailSelector);
              console.log('密码输入框选择器:', passwordSelector);
              throw new Error('登录表单未找到');
            }
            
            console.log('找到登录表单元素');
            console.log('邮箱输入框选择器:', emailSelector);
            console.log('密码输入框选择器:', passwordSelector);
            
            console.log('填写登录信息...');
            // 清空输入框并填写
            await page.click(emailSelector);
            await page.keyboard.down('Control');
            await page.keyboard.press('KeyA');
            await page.keyboard.up('Control');
            await page.type(emailSelector, process.env.LOGIN_EMAIL);
            
            await page.click(passwordSelector);
            await page.keyboard.down('Control');
            await page.keyboard.press('KeyA');
            await page.keyboard.up('Control');
            await page.type(passwordSelector, process.env.LOGIN_PASSWORD);
            
            console.log('查找登录按钮...');
            // 查找并点击登录按钮（多种可能的选择器）
            const loginButtonSelectors = [
              'button[type="submit"]',
              'input[type="submit"]',
              'button:contains("登录")',
              'button:contains("Login")',
              'button:contains("Sign in")',
              '.btn-primary',
              '.login-btn',
              'form button',
              'button'
            ];
            
            let loginButton = null;
            for (const selector of loginButtonSelectors) {
              try {
                loginButton = await page.$(selector);
                if (loginButton) {
                  console.log('找到登录按钮，选择器:', selector);
                  break;
                }
              } catch (e) {
                // 继续尝试下一个选择器
              }
            }
            
            if (loginButton) {
              console.log('点击登录按钮...');
              await loginButton.click();
            } else {
              console.log('未找到登录按钮，尝试按Enter键提交表单...');
              await page.keyboard.press('Enter');
            }
            
            console.log('等待页面跳转...');
            // 等待跳转到管理页面或登录完成
            await new Promise(resolve => setTimeout(resolve, 5000));
            
            // 检查是否跳转到管理页面
            const currentUrl = page.url();
            console.log('当前页面URL:', currentUrl);
            
            if (currentUrl.includes('searcade.com/en/admin')) {
              console.log('✅ 登录成功！已跳转到管理页面');
              process.exit(0);
            } else {
              // 尝试直接访问管理页面验证登录状态
              console.log('尝试访问管理页面验证登录状态...');
              await page.goto('https://searcade.com/en/admin', {
                waitUntil: 'networkidle2',
                timeout: 30000
              });
              
              const finalUrl = page.url();
              console.log('最终页面URL:', finalUrl);
              
              if (finalUrl.includes('searcade.com/en/admin')) {
                console.log('✅ 登录成功！可以访问管理页面');
                process.exit(0);
              } else {
                console.log('❌ 登录失败：未能访问管理页面');
                
                // 检查是否有错误消息
                const errorElements = await page.$$('.error, .alert-danger, [class*="error"]');
                if (errorElements.length > 0) {
                  for (const element of errorElements) {
                    const text = await element.textContent();
                    console.log('错误信息:', text);
                  }
                }
                
                process.exit(1);
              }
            }
            
          } catch (error) {
            console.error('登录过程中发生错误:', error.message);
            process.exit(1);
          } finally {
            if (browser) {
              await browser.close();
            }
          }
        })();
        EOF
        
        node login.js
        
    - name: Login Status
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          echo "登录任务执行成功"
        else
          echo "登录任务执行失败"
          exit 1
        fi
