name: Auto Login to Searcade

on:
  schedule:
    # 每三天执行一次，UTC时间00:00
    - cron: '0 0 */3 * *'
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]  # 有修改时也执行
  pull_request:
    branches: [ main ]

jobs:
  login:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Playwright
      run: |
        npm init -y
        npm install playwright
        npx playwright install chromium
        
    - name: Auto Login
      env:
        LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      run: |
        cat > login.js << 'EOF'
        const { chromium } = require('playwright');
        
        (async () => {
          const browser = await chromium.launch();
          const page = await browser.newPage();
          
          try {
            console.log('访问登录页面...');
            await page.goto('https://searcade.userveria.com/login');
            
            console.log('等待页面加载...');
            await page.waitForLoadState('networkidle');
            
            // 额外等待，确保动态内容加载完成
            await page.waitForTimeout(3000);
            
            console.log('查找邮箱输入框...');
            // 尝试多种选择器
            const emailSelectors = [
              '#email_input',
              'input[name="email"]',
              'input[type="email"]',
              'input[type="text"]'
            ];
            
            let emailFound = false;
            for (const selector of emailSelectors) {
              try {
                await page.waitForSelector(selector, { timeout: 5000 });
                console.log(`找到邮箱输入框: ${selector}`);
                await page.fill(selector, process.env.LOGIN_EMAIL);
                emailFound = true;
                break;
              } catch (e) {
                console.log(`未找到邮箱输入框: ${selector}`);
              }
            }
            
            if (!emailFound) {
              console.log('❌ 未找到邮箱输入框');
              process.exit(1);
            }
            
            console.log('查找密码输入框...');
            const passwordSelectors = [
              '#password_input',
              'input[name="password"]',
              'input[type="password"]'
            ];
            
            let passwordFound = false;
            for (const selector of passwordSelectors) {
              try {
                await page.waitForSelector(selector, { timeout: 5000 });
                console.log(`找到密码输入框: ${selector}`);
                await page.fill(selector, process.env.LOGIN_PASSWORD);
                passwordFound = true;
                break;
              } catch (e) {
                console.log(`未找到密码输入框: ${selector}`);
              }
            }
            
            if (!passwordFound) {
              console.log('❌ 未找到密码输入框');
              process.exit(1);
            }
            
            console.log('查找登录按钮...');
            const buttonSelectors = [
              'button[type="submit"]',
              'input[type="submit"]',
              'button:has-text("Login")',
              'button:has-text("登录")',
              '.btn-primary'
            ];
            
            let buttonFound = false;
            for (const selector of buttonSelectors) {
              try {
                await page.waitForSelector(selector, { timeout: 5000 });
                console.log(`找到登录按钮: ${selector}`);
                await page.click(selector);
                buttonFound = true;
                break;
              } catch (e) {
                console.log(`未找到登录按钮: ${selector}`);
              }
            }
            
            if (!buttonFound) {
              console.log('❌ 未找到登录按钮，尝试按Enter键');
              await page.keyboard.press('Enter');
            }
            
            console.log('等待登录完成...');
            await page.waitForLoadState('networkidle');
            
            console.log('检查登录结果...');
            const currentUrl = page.url();
            console.log('当前URL:', currentUrl);
            
            if (currentUrl.includes('searcade.com/en/admin')) {
              console.log('✅ 登录成功！');
            } else {
              console.log('❌ 登录失败，当前URL:', currentUrl);
              process.exit(1);
            }
            
          } catch (error) {
            console.error('❌ 登录失败:', error.message);
            process.exit(1);
          } finally {
            await browser.close();
          }
        })();
        EOF
        
        node login.js
